/**
 * 权限点目录: 与后端 DataInitializer.PERMISSIONS 对齐 (75 个)
 * 命名规则: <模块>_<动作>
 */

export const PERMISSION = {
  // 物资主数据
  MATERIAL_MANAGE_VIEW: 'MATERIAL_MANAGE_VIEW',
  MATERIAL_MANAGE_CREATE: 'MATERIAL_MANAGE_CREATE',
  MATERIAL_MANAGE_EDIT: 'MATERIAL_MANAGE_EDIT',
  MATERIAL_CATEGORY_MANAGE_VIEW: 'MATERIAL_CATEGORY_MANAGE_VIEW',
  MATERIAL_CATEGORY_MANAGE_EDIT: 'MATERIAL_CATEGORY_MANAGE_EDIT',
  MATERIAL_UOM_MANAGE_VIEW: 'MATERIAL_UOM_MANAGE_VIEW',
  MATERIAL_UOM_MANAGE_EDIT: 'MATERIAL_UOM_MANAGE_EDIT',
  MATERIAL_ATTRIBUTE_MANAGE_EDIT: 'MATERIAL_ATTRIBUTE_MANAGE_EDIT',

  // 组织仓库
  ORG_MANAGE_VIEW: 'ORG_MANAGE_VIEW',
  ORG_MANAGE_CREATE: 'ORG_MANAGE_CREATE',
  ORG_MANAGE_EDIT: 'ORG_MANAGE_EDIT',

  // 库存
  INVENTORY_VIEW: 'INVENTORY_VIEW',
  INVENTORY_DETAIL_VIEW: 'INVENTORY_DETAIL_VIEW',
  INVENTORY_LEDGER_VIEW: 'INVENTORY_LEDGER_VIEW',
  BATCH_MANAGE_VIEW: 'BATCH_MANAGE_VIEW',
  BATCH_MANAGE_EDIT: 'BATCH_MANAGE_EDIT',

  // 入库
  STOCK_INBOUND_VIEW: 'STOCK_INBOUND_VIEW',
  STOCK_INBOUND_EXECUTE: 'STOCK_INBOUND_EXECUTE',

  // 科室申领/出库
  ISSUE_REQUEST_VIEW: 'ISSUE_REQUEST_VIEW',
  ISSUE_REQUEST_EDIT: 'ISSUE_REQUEST_EDIT',
  ISSUE_REQUEST_APPROVE: 'ISSUE_REQUEST_APPROVE',
  PICK_EXECUTE_VIEW: 'PICK_EXECUTE_VIEW',
  PICK_EXECUTE: 'PICK_EXECUTE',
  ISSUE_CONFIRM: 'ISSUE_CONFIRM',
  ISSUE_REVERSE: 'ISSUE_REVERSE',

  // 调拨
  STOCK_TRANSFER_VIEW: 'STOCK_TRANSFER_VIEW',
  STOCK_TRANSFER_CREATE: 'STOCK_TRANSFER_CREATE',
  STOCK_TRANSFER_APPROVE: 'STOCK_TRANSFER_APPROVE',
  STOCK_TRANSFER_EXECUTE: 'STOCK_TRANSFER_EXECUTE',

  // 盘点
  STOCK_COUNT_VIEW: 'STOCK_COUNT_VIEW',
  STOCK_COUNT_CREATE: 'STOCK_COUNT_CREATE',
  STOCK_COUNT_EXECUTE: 'STOCK_COUNT_EXECUTE',
  STOCK_COUNT_CONFIRM: 'STOCK_COUNT_CONFIRM',

  // 退库
  STOCK_RETURN_VIEW: 'STOCK_RETURN_VIEW',
  STOCK_RETURN_CREATE: 'STOCK_RETURN_CREATE',
  STOCK_RETURN_CONFIRM: 'STOCK_RETURN_CONFIRM',

  // 报废
  STOCK_SCRAP_VIEW: 'STOCK_SCRAP_VIEW',
  STOCK_SCRAP_CREATE: 'STOCK_SCRAP_CREATE',
  STOCK_SCRAP_APPROVE: 'STOCK_SCRAP_APPROVE',

  // 报表
  REPORT_VIEW: 'REPORT_VIEW',
  REPORT_SUPPLIER: 'REPORT_SUPPLIER',

  // 供应商
  SUPPLIER_VIEW: 'SUPPLIER_VIEW',
  SUPPLIER_EDIT: 'SUPPLIER_EDIT',
  SUPPLIER_MATERIAL_MANAGE_VIEW: 'SUPPLIER_MATERIAL_MANAGE_VIEW',
  SUPPLIER_MATERIAL_MANAGE_EDIT: 'SUPPLIER_MATERIAL_MANAGE_EDIT',

  // 采购
  PURCHASE_REQUEST_VIEW: 'PURCHASE_REQUEST_VIEW',
  PURCHASE_REQUEST_EDIT: 'PURCHASE_REQUEST_EDIT',
  PURCHASE_REQUEST_APPROVE: 'PURCHASE_REQUEST_APPROVE',
  PURCHASE_AGREEMENT_VIEW: 'PURCHASE_AGREEMENT_VIEW',
  PURCHASE_AGREEMENT_EDIT: 'PURCHASE_AGREEMENT_EDIT',
  PURCHASE_ORDER_VIEW: 'PURCHASE_ORDER_VIEW',
  PURCHASE_ORDER_CREATE: 'PURCHASE_ORDER_CREATE',
  PURCHASE_ORDER_APPROVE: 'PURCHASE_ORDER_APPROVE',
  PURCHASE_RECEIPT_VIEW: 'PURCHASE_RECEIPT_VIEW',
  PURCHASE_RECEIPT_REGISTER: 'PURCHASE_RECEIPT_REGISTER',
  PURCHASE_ACCEPTANCE_VIEW: 'PURCHASE_ACCEPTANCE_VIEW',
  PURCHASE_ACCEPTANCE_CREATE: 'PURCHASE_ACCEPTANCE_CREATE',
  PURCHASE_ACCEPTANCE_EXECUTE: 'PURCHASE_ACCEPTANCE_EXECUTE',
  ACCEPTANCE_EXCEPTION: 'ACCEPTANCE_EXCEPTION',

  // 用户与角色
  USER_MANAGE_VIEW: 'USER_MANAGE_VIEW',
  USER_MANAGE_EDIT: 'USER_MANAGE_EDIT',
  ROLE_MANAGE_VIEW: 'ROLE_MANAGE_VIEW',
  ROLE_MANAGE_EDIT: 'ROLE_MANAGE_EDIT',
  DATA_SCOPE_MANAGE: 'DATA_SCOPE_MANAGE',

  // 工作台
  DASHBOARD_VIEW: 'DASHBOARD_VIEW',
  SEARCH_VIEW: 'SEARCH_VIEW',
  MESSAGE_VIEW: 'MESSAGE_VIEW',
  MESSAGE_MANAGE: 'MESSAGE_MANAGE',
  APPROVAL_CENTER: 'APPROVAL_CENTER',
  DOCUMENT_VIEW: 'DOCUMENT_VIEW',
  ALERT_VIEW: 'ALERT_VIEW',

  // 系统
  AUDIT_LOG_VIEW: 'AUDIT_LOG_VIEW',
  SYSTEM_PARAM_MANAGE: 'SYSTEM_PARAM_MANAGE',
  API_MONITOR_VIEW: 'API_MONITOR_VIEW',
  DATA_IMPORT_EXPORT: 'DATA_IMPORT_EXPORT',
} as const

export type PermissionCode = (typeof PERMISSION)[keyof typeof PERMISSION]

/**
 * 权限码按菜单模块分组 (角色配置弹窗用)
 * 顺序即展示顺序; 组内权限码需与 PERMISSION 对齐
 */
export const PERMISSION_GROUPS: { title: string; codes: PermissionCode[] }[] = [
  {
    title: '物资主数据',
    codes: [
      PERMISSION.MATERIAL_MANAGE_VIEW, PERMISSION.MATERIAL_MANAGE_CREATE, PERMISSION.MATERIAL_MANAGE_EDIT,
      PERMISSION.MATERIAL_CATEGORY_MANAGE_VIEW, PERMISSION.MATERIAL_CATEGORY_MANAGE_EDIT,
      PERMISSION.MATERIAL_UOM_MANAGE_VIEW, PERMISSION.MATERIAL_UOM_MANAGE_EDIT,
      PERMISSION.MATERIAL_ATTRIBUTE_MANAGE_EDIT,
    ],
  },
  {
    title: '组织与仓库',
    codes: [PERMISSION.ORG_MANAGE_VIEW, PERMISSION.ORG_MANAGE_CREATE, PERMISSION.ORG_MANAGE_EDIT],
  },
  {
    title: '库存查询',
    codes: [
      PERMISSION.INVENTORY_VIEW, PERMISSION.INVENTORY_DETAIL_VIEW, PERMISSION.INVENTORY_LEDGER_VIEW,
      PERMISSION.BATCH_MANAGE_VIEW, PERMISSION.BATCH_MANAGE_EDIT,
    ],
  },
  {
    title: '入库管理',
    codes: [PERMISSION.STOCK_INBOUND_VIEW, PERMISSION.STOCK_INBOUND_EXECUTE],
  },
  {
    title: '科室申领 / 出库',
    codes: [
      PERMISSION.ISSUE_REQUEST_VIEW, PERMISSION.ISSUE_REQUEST_EDIT, PERMISSION.ISSUE_REQUEST_APPROVE,
      PERMISSION.PICK_EXECUTE_VIEW, PERMISSION.PICK_EXECUTE,
      PERMISSION.ISSUE_CONFIRM, PERMISSION.ISSUE_REVERSE,
    ],
  },
  {
    title: '库存调拨',
    codes: [
      PERMISSION.STOCK_TRANSFER_VIEW, PERMISSION.STOCK_TRANSFER_CREATE,
      PERMISSION.STOCK_TRANSFER_APPROVE, PERMISSION.STOCK_TRANSFER_EXECUTE,
    ],
  },
  {
    title: '盘点管理',
    codes: [
      PERMISSION.STOCK_COUNT_VIEW, PERMISSION.STOCK_COUNT_CREATE,
      PERMISSION.STOCK_COUNT_EXECUTE, PERMISSION.STOCK_COUNT_CONFIRM,
    ],
  },
  {
    title: '退库管理',
    codes: [PERMISSION.STOCK_RETURN_VIEW, PERMISSION.STOCK_RETURN_CREATE, PERMISSION.STOCK_RETURN_CONFIRM],
  },
  {
    title: '报废管理',
    codes: [PERMISSION.STOCK_SCRAP_VIEW, PERMISSION.STOCK_SCRAP_CREATE, PERMISSION.STOCK_SCRAP_APPROVE],
  },
  {
    title: '采购管理',
    codes: [
      PERMISSION.PURCHASE_REQUEST_VIEW, PERMISSION.PURCHASE_REQUEST_EDIT, PERMISSION.PURCHASE_REQUEST_APPROVE,
      PERMISSION.PURCHASE_AGREEMENT_VIEW, PERMISSION.PURCHASE_AGREEMENT_EDIT,
      PERMISSION.PURCHASE_ORDER_VIEW, PERMISSION.PURCHASE_ORDER_CREATE, PERMISSION.PURCHASE_ORDER_APPROVE,
      PERMISSION.PURCHASE_RECEIPT_VIEW, PERMISSION.PURCHASE_RECEIPT_REGISTER,
      PERMISSION.PURCHASE_ACCEPTANCE_VIEW, PERMISSION.PURCHASE_ACCEPTANCE_CREATE,
      PERMISSION.PURCHASE_ACCEPTANCE_EXECUTE, PERMISSION.ACCEPTANCE_EXCEPTION,
    ],
  },
  {
    title: '供应商管理',
    codes: [
      PERMISSION.SUPPLIER_VIEW, PERMISSION.SUPPLIER_EDIT,
      PERMISSION.SUPPLIER_MATERIAL_MANAGE_VIEW, PERMISSION.SUPPLIER_MATERIAL_MANAGE_EDIT,
    ],
  },
  {
    title: '报表中心',
    codes: [PERMISSION.REPORT_VIEW, PERMISSION.REPORT_SUPPLIER],
  },
  {
    title: '工作台',
    codes: [
      PERMISSION.DASHBOARD_VIEW, PERMISSION.APPROVAL_CENTER, PERMISSION.SEARCH_VIEW,
      PERMISSION.MESSAGE_VIEW, PERMISSION.MESSAGE_MANAGE,
      PERMISSION.DOCUMENT_VIEW, PERMISSION.ALERT_VIEW,
    ],
  },
  {
    title: '用户与角色',
    codes: [
      PERMISSION.USER_MANAGE_VIEW, PERMISSION.USER_MANAGE_EDIT,
      PERMISSION.ROLE_MANAGE_VIEW, PERMISSION.ROLE_MANAGE_EDIT, PERMISSION.DATA_SCOPE_MANAGE,
    ],
  },
  {
    title: '系统管理',
    codes: [
      PERMISSION.AUDIT_LOG_VIEW, PERMISSION.SYSTEM_PARAM_MANAGE,
      PERMISSION.API_MONITOR_VIEW, PERMISSION.DATA_IMPORT_EXPORT,
    ],
  },
]

/**
 * 路由 path -> 主权限码 (VIEW 类)
 * 用于: 路由守卫 + 侧栏菜单过滤
 * undefined 表示该路由无需权限校验 (任何登录用户可见)
 */
export const ROUTE_PERMISSION: Record<string, PermissionCode | undefined> = {
  // /dashboard 为登录落地页, 不设权限门槛 (任何登录用户可见)
  '/approvals': PERMISSION.APPROVAL_CENTER,
  '/messages': PERMISSION.MESSAGE_VIEW,
  '/documents': PERMISSION.DOCUMENT_VIEW,
  '/search': PERMISSION.SEARCH_VIEW,

  '/stock/overview': PERMISSION.INVENTORY_VIEW,
  '/stock/query': PERMISSION.INVENTORY_DETAIL_VIEW,
  '/stock/inbound': PERMISSION.STOCK_INBOUND_VIEW,
  '/stock/outbound': PERMISSION.ISSUE_REQUEST_VIEW,
  '/stock/transfer': PERMISSION.STOCK_TRANSFER_VIEW,
  '/stock/count': PERMISSION.STOCK_COUNT_VIEW,
  '/stock/expiry': PERMISSION.ALERT_VIEW,
  '/stock/alerts': PERMISSION.ALERT_VIEW,
  '/stock/scrap': PERMISSION.STOCK_SCRAP_VIEW,
  '/stock/return': PERMISSION.STOCK_RETURN_VIEW,

  '/issue/requests': PERMISSION.ISSUE_REQUEST_VIEW,
  '/purchase/orders': PERMISSION.PURCHASE_REQUEST_VIEW,

  '/report/inout': PERMISSION.REPORT_VIEW,
  '/report/center': PERMISSION.REPORT_VIEW,

  '/master/material': PERMISSION.MATERIAL_MANAGE_VIEW,
  '/master/warehouse': PERMISSION.ORG_MANAGE_VIEW,
  '/master/supplier': PERMISSION.SUPPLIER_VIEW,

  '/system/user': PERMISSION.USER_MANAGE_VIEW,
  '/system/org': PERMISSION.ORG_MANAGE_VIEW,
  '/system/log': PERMISSION.AUDIT_LOG_VIEW,
  '/system/param': PERMISSION.SYSTEM_PARAM_MANAGE,
  '/system/monitor': PERMISSION.API_MONITOR_VIEW,
}